/**
 * Seeds the Vigyanics product catalog and categories into Supabase.
 * Run after migration: pnpm --filter @workspace/api-server exec tsx src/lib/seed.ts
 */
import { supabaseAdmin } from "./supabase";

const CATEGORIES = [
  { name: "STEM Kits", slug: "stem-kits", description: "All-in-one science and technology kits", icon: "FlaskConical", color: "#00D4FF", sort_order: 1 },
  { name: "Robotics Kits", slug: "robotics", description: "Build and program real robots", icon: "Bot", color: "#00C896", sort_order: 2 },
  { name: "AI Learning Kits", slug: "ai-learning", description: "Machine learning & computer vision", icon: "Brain", color: "#8B5CF6", sort_order: 3 },
  { name: "Electronics", slug: "electronics", description: "Components, modules and tools", icon: "Cpu", color: "#F59E0B", sort_order: 4 },
  { name: "Sensors & IoT", slug: "sensors-iot", description: "Smart sensors and connected devices", icon: "Wifi", color: "#EF4444", sort_order: 5 },
  { name: "Arduino & Microcontrollers", slug: "arduino", description: "Microcontroller boards and accessories", icon: "Zap", color: "#00D4FF", sort_order: 6 },
  { name: "School Lab Equipment", slug: "school-lab", description: "Classroom and innovation lab gear", icon: "School", color: "#00C896", sort_order: 7 },
  { name: "DIY Science Projects", slug: "diy-science", description: "Fun science project kits", icon: "Lightbulb", color: "#8B5CF6", sort_order: 8 },
  { name: "Competition Kits", slug: "competition", description: "Ready for hackathons and olympiads", icon: "Trophy", color: "#F59E0B", sort_order: 9 },
  { name: "Accessories", slug: "accessories", description: "Tools, storage and learning materials", icon: "Package", color: "#EF4444", sort_order: 10 },
];

async function seed() {
  console.log("Seeding categories...");

  // Upsert categories
  const { data: cats, error: catErr } = await supabaseAdmin
    .from("categories")
    .upsert(
      CATEGORIES.map((c) => ({ ...c, is_active: true })),
      { onConflict: "slug" }
    )
    .select();

  if (catErr) {
    console.error("Category seed error:", catErr.message);
    return;
  }
  console.log(`Seeded ${cats?.length} categories.`);

  const catMap = new Map((cats ?? []).map((c: { slug: string; id: number }) => [c.slug, c.id]));

  const PRODUCTS = [
    {
      name: "Vigyanics Robotics Starter Kit",
      short_description: "Build 5 robots with one kit. Beginner-friendly with expert-designed PCB.",
      long_description: "The ultimate beginner robotics kit designed by Vigyanics experts. Build 5 different robots with a single kit — line follower, obstacle avoider, remote-controlled bot, light seeker, and maze solver. Includes a custom-designed PCB, all components, and a step-by-step project book.",
      price: 2499,
      sale_price: null,
      sku: "VIG-001",
      quantity: 48,
      category_id: catMap.get("robotics"),
      tags: ["robotics", "beginner", "arduino", "line-follower"],
      status: "published",
      stock_status: "in_stock",
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: false,
      is_trending: false,
      age_group: "10+ years",
      rating: 4.8,
      review_count: 312,
      color_accent: "#00C896",
      features: ["Custom PCB board", "Arduino Nano", "2x DC motors + wheels", "L298N motor driver", "5x IR sensors", "HC-SR04 ultrasonic sensor", "9V battery holder", "Project book (50 pages)", "Jumper wires & tools"],
      specifications: { "Age Group": "10+ years", "Difficulty": "Beginner-Intermediate", "Programming Language": "C++ (Arduino IDE)", "Power": "9V battery / USB", "Projects": "5 different robots", "Book Included": "Yes (50 pages)" },
    },
    {
      name: "AI Vision Camera Kit",
      short_description: "Raspberry Pi 4 + Camera + TensorFlow Lite. 10 AI projects included.",
      long_description: "Learn computer vision and machine learning with this comprehensive AI kit. Includes a Raspberry Pi 4 (2GB), camera module, pre-loaded AI OS with TensorFlow Lite, and 10 guided projects covering face recognition, object detection, gesture control, and more.",
      price: 6499,
      sale_price: 4999,
      sku: "VIG-002",
      quantity: 23,
      category_id: catMap.get("ai-learning"),
      tags: ["ai", "raspberry-pi", "computer-vision", "machine-learning"],
      status: "published",
      stock_status: "low_stock",
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: true,
      is_trending: true,
      age_group: "14+ years",
      rating: 4.9,
      review_count: 187,
      color_accent: "#8B5CF6",
      features: ["Raspberry Pi 4 (2GB)", "8MP Camera Module", "32GB Pre-loaded SD Card", "Power adapter", "HDMI cable", "Acrylic case", "Project guide (100 pages)", "Online course access (6 months)"],
      specifications: { "Age Group": "14+ years", "Difficulty": "Intermediate-Advanced", "Programming Language": "Python", "AI Framework": "TensorFlow Lite", "Projects": "10 AI projects", "Internet": "Required for some projects" },
    },
    {
      name: "STEM Electronics Explorer Kit",
      short_description: "200+ components, multimeter, breadboard + 30 experiments. School-proven.",
      long_description: "A complete STEM learning toolkit for students new to electronics. Includes 200+ components, breadboard, multimeter, and a structured 30-experiment workbook covering circuits, LEDs, sensors, and basic Arduino projects. Used in 60+ Vigyanics partner schools.",
      price: 1799,
      sale_price: 1299,
      sku: "VIG-003",
      quantity: 120,
      category_id: catMap.get("stem-kits"),
      tags: ["stem", "electronics", "beginner", "breadboard", "school"],
      status: "published",
      stock_status: "in_stock",
      is_featured: true,
      is_best_seller: true,
      is_new_arrival: false,
      is_trending: false,
      age_group: "8+ years",
      rating: 4.7,
      review_count: 445,
      color_accent: "#00D4FF",
      features: ["Breadboard (830 tie points)", "Digital multimeter", "Arduino UNO", "200+ components", "LED assortment (50 pcs)", "Resistor kit", "USB cable", "Experiment workbook (80 pages)"],
      specifications: { "Age Group": "8+ years", "Difficulty": "Beginner", "Components": "200+", "Experiments": "30", "Schools Using": "60+", "Curriculum": "CBSE aligned" },
    },
    {
      name: "Smart Home IoT Builder Kit",
      short_description: "Build real home automation with NodeMCU, MQTT, and custom app.",
      long_description: "Build a real working smart home automation system with this comprehensive IoT kit. Control lights, fans, temperature monitoring, and security using NodeMCU, MQTT, and a custom Android app. Perfect for understanding the Internet of Things end-to-end.",
      price: 4299,
      sale_price: 3499,
      sku: "VIG-004",
      quantity: 35,
      category_id: catMap.get("sensors-iot"),
      tags: ["iot", "smart-home", "nodemcu", "mqtt", "automation"],
      status: "published",
      stock_status: "in_stock",
      is_featured: true,
      is_best_seller: false,
      is_new_arrival: true,
      is_trending: true,
      age_group: "12+ years",
      rating: 4.6,
      review_count: 203,
      color_accent: "#00D4FF",
      features: ["2x NodeMCU ESP8266", "DHT22 temperature sensor", "PIR motion sensor", "Relay module (4 channel)", "OLED display", "IR receiver & remote", "Jumper wires", "Enclosure", "Project guide"],
      specifications: { "Age Group": "12+ years", "Difficulty": "Intermediate", "Protocol": "MQTT / HTTP", "Connectivity": "Wi-Fi", "App": "Android APK included", "Cloud": "Optional" },
    },
    {
      name: "Line Follower Robot Pro Kit",
      short_description: "Competition-grade line follower with 8-sensor array and PID control code.",
      long_description: "Build a competition-grade line follower robot from scratch. This kit includes a custom chassis, 8-sensor array, L298N motor driver, and optimized PID control code. Used by Vigyanics students who have won at state and national robotics competitions.",
      price: 2399,
      sale_price: 1899,
      sku: "VIG-005",
      quantity: 67,
      category_id: catMap.get("robotics"),
      tags: ["robotics", "competition", "line-follower", "pid"],
      status: "published",
      stock_status: "in_stock",
      is_featured: false,
      is_best_seller: true,
      is_new_arrival: false,
      is_trending: true,
      age_group: "12+ years",
      rating: 4.8,
      review_count: 567,
      color_accent: "#00C896",
      features: ["Custom aluminum chassis", "2x High-speed motors", "L298N motor driver", "8-sensor IR array", "Arduino UNO", "Li-Po battery + charger", "PID source code (downloadable)", "Assembly guide"],
      specifications: { "Age Group": "12+ years", "Difficulty": "Intermediate", "Speed": "Up to 1.5m/s", "Sensors": "8 IR", "Control": "PID algorithm", "Competition Ready": "Yes" },
    },
    {
      name: "Arduino Advanced Learning Bundle",
      short_description: "3 Arduino boards + 500+ components + 50 projects + video course.",
      long_description: "The most comprehensive Arduino learning bundle available. Includes Arduino UNO, Mega, and Nano, plus 500+ components covering every major sensor, module, and interface. Comes with 50 project tutorials and lifetime access to our Arduino video course.",
      price: 2899,
      sale_price: 2199,
      sku: "VIG-006",
      quantity: 89,
      category_id: catMap.get("arduino"),
      tags: ["arduino", "microcontroller", "components", "comprehensive"],
      status: "published",
      stock_status: "in_stock",
      is_featured: false,
      is_best_seller: true,
      is_new_arrival: false,
      is_trending: false,
      age_group: "10+ years",
      rating: 4.7,
      review_count: 389,
      color_accent: "#F59E0B",
      features: ["Arduino UNO R3", "Arduino Mega 2560", "Arduino Nano (3 pcs)", "500+ components", "Sensor kit (40 sensors)", "Display modules (LCD, OLED, 7-seg)", "Motor driver shields", "Breadboard + wires", "Project booklet"],
      specifications: { "Age Group": "10+ years", "Difficulty": "Beginner-Advanced", "Boards": "3 Arduino boards", "Components": "500+", "Projects": "50", "Video Course": "Lifetime access" },
    },
    {
      name: "Sensor Lab Pack (40 Sensors)",
      short_description: "40 sensors: temperature, motion, light, gas, ultrasonic, and more.",
      long_description: "A comprehensive collection of 40 different sensors essential for STEM and robotics projects. Each sensor comes individually packed with a datasheet and basic code snippet. Compatible with Arduino, Raspberry Pi, and NodeMCU.",
      price: 1499,
      sale_price: 999,
      sku: "VIG-007",
      quantity: 156,
      category_id: catMap.get("sensors-iot"),
      tags: ["sensors", "iot", "arduino", "raspberry-pi"],
      status: "published",
      stock_status: "in_stock",
      is_featured: false,
      is_best_seller: true,
      is_new_arrival: false,
      is_trending: false,
      age_group: "8+ years",
      rating: 4.6,
      review_count: 712,
      color_accent: "#EF4444",
      features: ["DHT11/DHT22 temperature sensor", "HC-SR04 ultrasonic sensor", "PIR motion sensor", "MQ-series gas sensors (5 types)", "Light-dependent resistor", "Soil moisture sensor", "Flame sensor", "Vibration sensor", "And 32 more..."],
      specifications: { "Age Group": "8+ years", "Total Sensors": "40", "Compatibility": "Arduino, RPi, NodeMCU", "Datasheets": "Included for all", "Code Snippets": "Included for all" },
    },
    {
      name: "ATL Lab Starter Pack",
      short_description: "Complete ATL setup for 30 students: hardware + software + 1yr mentorship.",
      long_description: "Everything a school needs to launch an Atal Tinkering Lab in one curated package. Supports 30 students simultaneously with 5 different project stations. Includes all hardware, software licenses, a 1-year Vigyanics mentorship program, and documentation support for NITI Aayog reporting.",
      price: 34999,
      sale_price: 24999,
      sku: "VIG-008",
      quantity: 12,
      category_id: catMap.get("school-lab"),
      tags: ["atl", "school", "lab", "institution", "bulk"],
      status: "published",
      stock_status: "low_stock",
      is_featured: true,
      is_best_seller: false,
      is_new_arrival: false,
      is_trending: false,
      age_group: "All ages",
      rating: 4.9,
      review_count: 48,
      color_accent: "#00C896",
      features: ["10x Robotics Starter Kits", "5x AI Vision Camera Kits", "10x STEM Explorer Kits", "5x IoT Builder Kits", "30x Individual component kits", "Tool station (soldering, cutting, measuring)", "Storage cabinet", "1-year mentorship subscription"],
      specifications: { "Student Capacity": "30 simultaneous", "Age Group": "Classes 5-12", "Duration": "1 year program", "Mentorship": "Included (12 sessions)", "Reporting Support": "NITI Aayog compliant", "Warranty": "1 year" },
    },
    {
      name: "Drone Builder Pro Kit",
      short_description: "Build a real quadcopter drone from scratch with FPV camera.",
      long_description: "Build a fully functional quadcopter drone from scratch. This advanced kit includes a carbon fiber frame, Betaflight flight controller, brushless motors, ESCs, and FPV camera. Students learn aerodynamics, control systems, and electronics through a structured build process.",
      price: 7299,
      sale_price: 5499,
      sku: "VIG-009",
      quantity: 18,
      category_id: catMap.get("competition"),
      tags: ["drone", "competition", "advanced", "fpv"],
      status: "published",
      stock_status: "low_stock",
      is_featured: true,
      is_best_seller: false,
      is_new_arrival: true,
      is_trending: true,
      age_group: "15+ years",
      rating: 4.7,
      review_count: 134,
      color_accent: "#8B5CF6",
      features: ["Carbon fiber quadcopter frame", "Betaflight F4 flight controller", "4x Brushless motors (2300KV)", "4x 30A ESCs", "FPV camera (700TVL)", "2.4GHz radio transmitter + receiver", "LiPo battery (3S, 2200mAh) + charger", "Propellers (4 pairs)", "Build guide"],
      specifications: { "Age Group": "15+ years", "Difficulty": "Advanced", "Frame Size": "250mm", "Flight Time": "~12 minutes", "FPV": "Yes, analog", "Competition": "Ready for FPV racing" },
    },
    {
      name: "Science Project DIY Kit (10-in-1)",
      short_description: "10 science fair projects: windmill, solar, hydraulics, electrochemistry and more.",
      long_description: "Ten fascinating science project kits in one box. Perfect for school science fairs and exhibitions. Projects include a working windmill, solar panel circuit, electrochemistry demonstration, simple hydraulics, and more. Each project comes with materials and a detailed guide.",
      price: 1099,
      sale_price: 799,
      sku: "VIG-010",
      quantity: 234,
      category_id: catMap.get("diy-science"),
      tags: ["science", "diy", "school-fair", "beginner"],
      status: "published",
      stock_status: "in_stock",
      is_featured: false,
      is_best_seller: true,
      is_new_arrival: false,
      is_trending: false,
      age_group: "8+ years",
      rating: 4.5,
      review_count: 823,
      color_accent: "#F59E0B",
      features: ["Mini windmill materials", "Solar panel (5V 1W)", "Electrochemistry kit", "Hydraulics syringe kit", "Magnets & electromagnet materials", "Chromatography paper", "Volcano chemistry kit", "Periscope mirrors", "Bridge strength kit", "Water purification demo kit"],
      specifications: { "Age Group": "8+ years", "Difficulty": "Beginner", "Projects": "10", "Duration": "2-4 hours each", "Science Fair": "Ready to present", "CBSE Syllabus": "Aligned" },
    },
    {
      name: "AI Chatbot & NLP Starter Kit",
      short_description: "Build AI chatbots with NLP. Includes Raspberry Pi Zero 2W + voice recognition.",
      long_description: "Build your own AI chatbot and explore natural language processing with this hands-on kit. Powered by Raspberry Pi Zero 2W with pre-installed libraries including NLTK, spaCy, and a custom chatbot framework. Includes projects for sentiment analysis, intent classification, and voice recognition.",
      price: 4499,
      sale_price: 3299,
      sku: "VIG-011",
      quantity: 27,
      category_id: catMap.get("ai-learning"),
      tags: ["ai", "nlp", "chatbot", "python"],
      status: "published",
      stock_status: "in_stock",
      is_featured: false,
      is_best_seller: false,
      is_new_arrival: true,
      is_trending: true,
      age_group: "14+ years",
      rating: 4.8,
      review_count: 97,
      color_accent: "#8B5CF6",
      features: ["Raspberry Pi Zero 2W", "Microphone module", "Speaker + amplifier", "16GB pre-loaded SD card", "Power adapter", "Display cable adapter", "Project workbook (60 pages)", "6-month online course"],
      specifications: { "Age Group": "14+ years", "Difficulty": "Intermediate-Advanced", "AI Frameworks": "NLTK, spaCy", "Programming": "Python 3", "Projects": "6 NLP projects", "Voice": "Speech recognition included" },
    },
    {
      name: "Hackathon Ready Pack",
      short_description: "Complete hackathon bundle for a team of 4. Used at SIH & ATL Marathon.",
      long_description: "Everything a team of 4 students needs for a 24-48 hour hackathon or innovation challenge. Includes components for hardware, software, and IoT projects — whatever challenge theme comes up, this pack covers it. Used by Vigyanics teams at SIH, ATL Marathon, and state competitions.",
      price: 5999,
      sale_price: 4299,
      sku: "VIG-012",
      quantity: 31,
      category_id: catMap.get("competition"),
      tags: ["hackathon", "competition", "team", "comprehensive"],
      status: "published",
      stock_status: "in_stock",
      is_featured: false,
      is_best_seller: false,
      is_new_arrival: false,
      is_trending: false,
      age_group: "13+ years",
      rating: 4.9,
      review_count: 156,
      color_accent: "#F59E0B",
      features: ["Raspberry Pi 4 (2GB)", "Arduino UNO + Mega", "NodeMCU ESP8266 (2 pcs)", "Sensor mega-pack (20 sensors)", "Display modules (2 sizes)", "Battery packs (portable)", "Breadboards + wires (bulk)", "3D printing filament sample", "Team project planning booklet"],
      specifications: { "Team Size": "Up to 4 students", "Age Group": "13+ years", "Duration": "24-72 hour hackathons", "Competitions": "SIH, ATL Marathon, State level", "Breadboards": "4 included", "Warranty": "6 months" },
    },
  ];

  console.log("Seeding products...");
  const { data: insertedProducts, error: prodErr } = await supabaseAdmin
    .from("products")
    .upsert(PRODUCTS, { onConflict: "sku" })
    .select("id, name");

  if (prodErr) {
    console.error("Product seed error:", prodErr.message);
    return;
  }
  console.log(`Seeded ${insertedProducts?.length} products.`);
  console.log("Seed complete!");
}

seed().catch(console.error);
